[font]
size = 12

[font.normal]
family = "Iosevka"

[font.bold]
family = "Iosevka"

[font.italic]
family = "Iosevka"

[font.bold_italic]
family = "Iosevka"

[window]
opacity = 0.85

[window.padding]
x = 4
y = 4
